apiVersion: v1
kind: Secret
metadata:
  name: backstage-basic-auth
  namespace: backstage
type: Opaque
stringData:
  # Username: admin
  # Password: AdminPassword123
  .htpasswd: |
    admin:$2y$05$WZ5Qr3qVJGKr.7.3XqN8F.XxH3Q8vQf3Z8uXqKqN8F.XxH3Q8vQf3
